title: 'Matr채ddning i Sverige'
default_lang: sv
author:
  name: Bruno
  email: bruno@solikyl.se
taxonomies:
  - category
  - tag
metadata:
  description: 'R채dda mat som skulle sl채ngas genom dela ut till obegr채nsat'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
